name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "snehanaraniwal" --password-stdin

      - name: Build Docker image
        run: docker build -t snehanaraniwal/fastapi-app:v1 .

      - name: Push Docker image to Docker Hub
        run: docker push snehanaraniwal/fastapi-app:v1
